### ISSUE TITLE
[BUG] (Freezing game whit allotted 12gb of ram)

### ISSUE THREAD

**Issue by Zero-bo** [Admiral-Sebastian/TheWanderers#2]
**Describe the bug**
Freezing game, probable cause ram (leak) but it has the above min recommended amount of ram allotted, 12mb for single player.'
Game runs fine for a bit but then freezes become more and more frequent, I open up the debug menu and noticed that once the game unfroze the ram would immediately be at 60%
 I have also noticed that despite the game being allotted 12mb of ram it is only using 11mb

**To Reproduce**
Play for 10min to 15min, open up debug menu (f3) to see mem usage percentage once it starts freezing

**Expected behavior**
mem to dump entirely

**Comment by Zero-bo** [comment]
Also to clarify this issue was also occurring in the previous version of the modpack 5.3.0

**Comment by Admiral-Sebastian** [comment]
12mb? do you mean 12gb?

**Comment by Admiral-Sebastian** [comment]
Are you also using optifine?

**Comment by Zero-bo** [comment]
Yes and yes 12gb,  lol I let myself get carried away by using mb since CurseForge mem slider keeps reading it at mb.

**Comment by Admiral-Sebastian** [comment]
If you, are you able to send your PC specs

**Comment by Zero-bo** [comment]
[SysInfoSpecs.txt](https://github.com/Admiral-Sebastian/TheWanderers/files/6039633/SysInfoSpecs.txt)

**Comment by Admiral-Sebastian** [comment]
Expect an update to the modpack in a few days. There will also be some optifine settings guide to make the game run as smooth as it can. Since this modpack is one of the largest modpack there is. You are bound to have lag spikes here and there.

**Comment by Zero-bo** [comment]
Oh I can expect those for sure but the reason that brought me here was the lag spike were increasingly frequent and would always grind the game to a halt by having said freezes occur back to back, and these were large ones where the game would freeze for a min and then would take about a few seconds for the frame rate to go back up, it would get to a point where it would occur aprox every 2 mins. Hopefully the update and the settings can fix that.

**Comment by Admiral-Sebastian** [comment]
It's understandable, I have those said lag spikes. But fortunately, mine was every 2 hours or more or none at all. In the end, I get a stable 60 to 70fps.

**Comment by Admiral-Sebastian** [comment]
I uploaded the latest update 5.7.1 read the changelogs for directions for Optifine configuration

**Comment by Admiral-Sebastian** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BUG] (Freezing game whit allotted 12gb of ram) #2](https://trello.com/c/612jpg2s/1-bug-freezing-game-whit-allotted-12gb-of-ram-2)
